version: 2.1

orbs:
  codecov: codecov/codecov@1.1.1

executors:
  ubuntu-16_04:
    docker:
    - image: ubuntu:xenial-20201014

commands:
  install-base:
    steps:
    - run:
        name: Update apt and install base tools
        # - Curl needed by codecov, wget by us
        # - git soft-required by the `checkout` step, but needed by us to
        #   generate version info
        command: |
          apt update
          apt install -y ninja-build lcov wget curl git

  install-gcc-4_8:
    steps:
    - run:
        name: Install GCC 4.8
        command: |
          apt install -y g++-4.8
          echo 'export CXX=g++-4.8' >> $BASH_ENV

  install-cmake-3_4:
    steps:
    - run:
        name: Install CMake 3.4
        command: |
          mkdir -p $HOME/cmake && cd $HOME/cmake
          wget -nc --no-check-certificate https://cmake.org/files/v3.4/cmake-3.4.3-Linux-x86_64.tar.gz
          tar --strip-components=1 -xzf cmake-3.4.3-Linux-x86_64.tar.gz
          echo 'export PATH=$HOME/cmake/bin:$PATH' >> $BASH_ENV
          source $BASH_ENV && cmake --version | grep 3.4

  make-expected-linux-dirs:
    steps:
    - run:
        name: Create files expected by Utility::Directory tests on Linux
        command: |
          mkdir -p ~/.config/autostart
          mkdir -p ~/.local

  build:
    parameters:
      script:
        type: string
    steps:
    - checkout
    - run:
        name: Build & test
        command: |
          if [ "$BUILD_STATIC" != "ON" ]; then export BUILD_STATIC=OFF; fi
          if [ "$BUILD_DEPRECATED" != "OFF" ]; then export BUILD_DEPRECATED=ON; fi
          ./package/ci/<< parameters.script >>

  lcov:
    steps:
    - run:
        name: Collect code coverage
        command: |
          lcov $LCOV_EXTRA_OPTS --directory . --capture --output-file coverage.info > /dev/null
          lcov $LCOV_EXTRA_OPTS --extract coverage.info "*/src/Corrade/*" --output-file coverage.info > /dev/null
          lcov $LCOV_EXTRA_OPTS --remove coverage.info "*/Test/*" --output-file coverage.info > /dev/null
          lcov $LCOV_EXTRA_OPTS --remove coverage.info "*/build/src/Corrade/*" --output-file coverage.info > /dev/null
    - codecov/upload:
        file: coverage.info

jobs:
  linux:
    executor: ubuntu-16_04
    environment:
      CMAKE_CXX_FLAGS: --coverage
      LCOV_EXTRA_OPTS: --gcov-tool /usr/bin/gcov-4.8
      CONFIGURATION: Debug
    steps:
    - install-base
    - install-gcc-4_8
    - install-cmake-3_4
    - make-expected-linux-dirs
    - build:
        script: travis-desktop.sh
    - lcov

workflows:
  version: 2
  build:
    jobs:
    - linux
